version: '3'

services:
  my_service:
    image: iquestcrawler
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - UPSTASH_VECTOR_REST_URL=**
      - UPSTASH_VECTOR_REST_TOKEN=**
      - OPENAI_API_KEY=**